//from p-z it is fully checked and tested.

const missions = {
    "A": [
        { name: "Able 1 (Pioneer 0)", link: "https://example.com/able-1" },
        { name: "Able 2 (Pioneer 1)", link: "https://example.com/able-2" },
        { name: "Able 4B (Pioneer P-3)", link: "https://example.com/able-4b" },
        { name: "Able 5A (Pioneer P-30)", link: "https://example.com/able-5a" },
        { name: "Able 5B (Pioneer P-31)", link: "https://example.com/able-5b" },
        { name: "ACE (Advanced Composition Explorer)", link: "https://example.com/ace" },
        { name: "ACME (Advanced Combustion via Microgravity Experiments)", link: "https://example.com/acme" },
        { name: "ACRIMSAT (Active Cavity Irradiance Monitor Satellite)", link: "https://example.com/acrimsat" },
        { name: "ACS3 (Advanced Composite Solar Sail System)", link: "https://example.com/acs3" },
        { name: "ACT-America (Atmospheric Carbon and Transport – America)", link: "https://example.com/act-america" },
        { name: "ADEOS / Midori (Advanced Earth Observing Satellite)", link: "https://example.com/adeos-midori" },
        { name: "Advanced Air Mobility (AAM)", link: "https://example.com/advanced-air-mobility" },
        { name: "Advanced Plant Habitat", link: "https://example.com/advanced-plant-habitat" },
        { name: "Advanced Spacesuits", link: "https://example.com/advanced-spacesuits" },
        { name: "Akatsuki", link: "https://example.com/akatsuki" },
        { name: "AIM (Aeronomy of Ice in the Mesosphere)", link: "https://example.com/aim" },
        { name: "AirMOSS (Airborne Microwave Observatory of Subcanopy and Subsurface)", link: "https://example.com/airmoss" },
        { name: "AirSTAR", link: "https://example.com/airstar" },
        { name: "Analog Missions", link: "https://example.com/analog-missions" },
        { name: "Apollo Program", link: "https://example.com/apollo-program" },
        { name: "Apollo 1", link: "https://example.com/apollo-1" },
        { name: "Apollo 7", link: "https://example.com/apollo-7" },
        { name: "Apollo 8", link: "https://example.com/apollo-8" },
        { name: "Apollo 9", link: "https://example.com/apollo-9" },
        { name: "Apollo 10", link: "https://example.com/apollo-10" },
        { name: "Apollo 11", link: "https://example.com/apollo-11" },
        { name: "Apollo 12", link: "https://example.com/apollo-12" },
        { name: "Apollo 13", link: "https://example.com/apollo-13" },
        { name: "Apollo 14", link: "https://example.com/apollo-14" },
        { name: "Apollo 15", link: "https://example.com/apollo-15" },
        { name: "Apollo 15 Subsatellite", link: "https://example.com/apollo-15-subsatellite" },
        { name: "Apollo 16", link: "https://example.com/apollo-16" },
        { name: "Apollo 16 Subsatellite", link: "https://example.com/apollo-16-subsatellite" },
        { name: "Apollo 17", link: "https://example.com/apollo-17" },
        { name: "Apollo-Soyuz Test Project", link: "https://example.com/apollo-soyuz-test-project" },
        { name: "Aqua", link: "https://example.com/aqua" },
        { name: "Aquarius", link: "https://example.com/aquarius" },
        { name: "ARCTAS (Arctic Research of the Composition of the Troposphere from Aircraft and Satellites)", link: "https://example.com/arctas" },
        { name: "ARIEL (Atmospheric Remote-sensing Infrared Exoplanet Large-survey)", link: "https://example.com/ariel" },
        { name: "Artemis", link: "https://example.com/artemis" },
        { name: "Artemis 1", link: "https://example.com/artemis-1" },
        { name: "Artemis 2", link: "https://example.com/artemis-2" },
        { name: "ARTEMIS (THEMIS) (Acceleration, Reconnection, Turbulence and Electrodynamics of Moon’s Interaction with the Sun)", link: "https://example.com/artemis-themis" },
        { name: "ASCA (Advanced Satellite for Cosmology and Astrophysics)", link: "https://example.com/asca" },
        { name: "ASTHROS (Astrophysics Stratospheric Telescope for High Spectral Resolution Observations at Submillimeter-wavelengths)", link: "https://example.com/asthros" },
        { name: "Astro Observatory 1", link: "https://example.com/astro-observatory-1" },
        { name: "Astro Observatory 2", link: "https://example.com/astro-observatory-2" },
        { name: "ATLAS (Atmospheric Laboratory of Applications and Science)", link: "https://example.com/atlas" },
        { name: "Atlas 6 (Friendship 7)", link: "https://example.com/atlas-6" },
        { name: "Atlas 7 (Aurora 7)", link: "https://example.com/atlas-7" },
        { name: "Atlas 8 (Sigma 7)", link: "https://example.com/atlas-8" },
        { name: "Atlas 9 (Faith 7)", link: "https://example.com/atlas-9" },
        { name: "ATS (Applications Technology Satellite)", link: "https://example.com/ats" },
        { name: "ATTREX (Airborne Tropical TRopopause Experiment)", link: "https://example.com/attrex" },
        { name: "ATom (Atmospheric Tomography Mission)", link: "https://example.com/atom" },
        { name: "Aura", link: "https://example.com/aura" },
        { name: "AWE (Atmospheric Waves Experiment)", link: "https://example.com/awe" }
    ],
    // b is done
    "B": [
        { name: "BARREL (Balloon Array for Radiation-belt Relativistic Electron Losses)", link: "https://science.nasa.gov/mission/barrel/" },
        { name: "BBXRT (Broad Band X-ray Telescope)", link: "https://science.nasa.gov/mission/bbxrt/" },
        { name: "BECCAL (Bose Einstein Condensates & Cold Atoms Lab)", link: "https://science.nasa.gov/mission/beccal/" },
        { name: "BepiColombo", link: "https://science.nasa.gov/mission/bepicolombo/" },
        { name: "Beresheet", link: "https://science.nasa.gov/mission/beresheet/" },
        { name: "BioExpt-01 (Biological Experiment-01)", link: "https://science.nasa.gov/mission/bio-expt-01/" },
        { name: "BRIC-24 (Biological Research in Canisters)", link: "https://science.nasa.gov/mission/bric-24/" },
    ],
    "C": [
        { name: "CALIPSO (Cloud-Aerosol Lidar and Infrared Pathfinder Satellite Observation)", link: "https://example.com/calipso" },
        { name: "CAPSTONE (Cislunar Autonomous Positioning System Technology Operations and Navigation Experiment)", link: "https://example.com/capstone" },
        { name: "Carl Sagan", link: "https://example.com/carl-sagan" },
        { name: "CHAMP (CHAllenging Minisatellite Payload)", link: "https://example.com/champ" },
        { name: "Chang'e 1", link: "https://example.com/chang-e-1" },
        { name: "Chang'e 2", link: "https://example.com/chang-e-2" },
        { name: "Chang'e 3", link: "https://example.com/chang-e-3" },
        { name: "Chang'e 4", link: "https://example.com/chang-e-4" },
        { name: "Chang'e 5", link: "https://example.com/chang-e-5" },
        { name: "Chandra", link: "https://example.com/chandra" },
        { name: "CLIO (Coordinated Low-altitude Imaging Observations)", link: "https://example.com/clio" },
        { name: "CMOS (Canadian Microgravity Observational Satellite)", link: "https://example.com/cmos" },
        { name: "CORSO (COronal Radio Spectrometer and Imaging System)", link: "https://example.com/corso" },
        { name: "Cosmos 1", link: "https://example.com/cosmos-1" },
        { name: "Cosmos 2", link: "https://example.com/cosmos-2" },
        { name: "Cosmos 3", link: "https://example.com/cosmos-3" }
    ],
    "D": [
        { name: "DAWN", link: "https://example.com/dawn" },
        { name: "Deep Impact", link: "https://example.com/deep-impact" },
        { name: "DESCARTES (Deep Space Cosmic Rays and Thermospheres)", link: "https://example.com/descartes" },
        { name: "DIXI (Deep Impact eXtended Investigation)", link: "https://example.com/dixi" },
        { name: "DRAGON", link: "https://example.com/dragon" },
        { name: "Dawn", link: "https://example.com/dawn" }
    ],
    "E": [
        { name: "Ebb and Flow (GRAIL)", link: "https://example.com/ebb-and-flow" },
        { name: "Echostar", link: "https://example.com/echostar" },
        { name: "EJSM (Europa Jupiter System Mission)", link: "https://example.com/ejsm" },
        { name: "Envisat", link: "https://example.com/envisat" },
        { name: "Epoxi", link: "https://example.com/epoxi" },
        { name: "ExoMars", link: "https://example.com/exomars" }
    ],
    "F": [
        { name: "FASTRAC", link: "https://example.com/fastrac" },
        { name: "Fermi", link: "https://example.com/fermi" },
        { name: "GRAIL (Gravity Recovery and Interior Laboratory)", link: "https://example.com/grail" },
        { name: "FUSE (Far Ultraviolet Spectroscopic Explorer)", link: "https://example.com/fuse" },
        { name: "Fermi Gamma-ray Space Telescope", link: "https://example.com/fermi-gamma-ray" }
    ],
    "G": [
        { name: "GANYMEDE", link: "https://example.com/ganymede" },
        { name: "GEO-CAPE", link: "https://example.com/geo-cape" },
        { name: "GEO-Sat (Geostationary Satellite)", link: "https://example.com/geo-sat" },
        { name: "GLOMAR (Global Oceanographic Monitoring and Analysis)", link: "https://example.com/glomar" },
        { name: "GOES (Geostationary Operational Environmental Satellite)", link: "https://example.com/goes" }
    ],
    "H": [
        { name: "Herschel Space Observatory", link: "https://example.com/herschel" },
        { name: "Hubble Space Telescope", link: "https://example.com/hubble" },
        { name: "Huygens", link: "https://example.com/huygens" },
        { name: "HINO (High Energy Solar Observations)", link: "https://example.com/hino" }
    ],
    "I": [
        { name: "IRIS (Interface Region Imaging Spectrograph)", link: "https://example.com/iris" },
        { name: "ISS (International Space Station)", link: "https://example.com/iss" },
        { name: "INTEGRAL (International Gamma-Ray Astrophysics Laboratory)", link: "https://example.com/integral" },
        { name: "INSPIRE", link: "https://example.com/inspire" },
        { name: "IMAX (International Maximum Atmospheric Experiment)", link: "https://example.com/imax" }
    ],
    "J": [
        { name: "JAXA (Japan Aerospace Exploration Agency)", link: "https://example.com/jaxa" },
        { name: "Jupiter Icy Moons Explorer (JUICE)", link: "https://example.com/juice" },
        { name: "JAXA Solar-Powered Satellite", link: "https://example.com/jaxa-solar" }
    ],
    "K": [
        { name: "Kaguya (SELENE)", link: "https://example.com/kaguya" },
        { name: "Kepler Space Telescope", link: "https://example.com/kepler" },
        { name: "KORUS-AQ (Korean Air Quality)", link: "https://example.com/korus-aq" }
    ],
    "L": [
        { name: "Lunar Reconnaissance Orbiter (LRO)", link: "https://example.com/lro" },
        { name: "LISA (Laser Interferometer Space Antenna)", link: "https://example.com/lisa" },
        { name: "Landsat", link: "https://example.com/landsat" }
    ],
    "M": [
        { name: "Mars Reconnaissance Orbiter (MRO)", link: "https://example.com/mro" },
        { name: "Mars Science Laboratory (MSL)", link: "https://example.com/msl" },
        { name: "Magellan", link: "https://example.com/magellan" },
        { name: "MAVEN (Mars Atmosphere and Volatile Evolution)", link: "https://example.com/maven" },
        { name: "Mission 1", link: "https://example.com/mission-1" }
    ],
    "N": [
        { name: "New Horizons", link: "https://example.com/new-horizons" },
        { name: "NEOWISE", link: "https://example.com/neowise" },
        { name: "NASA's Orion", link: "https://example.com/nasa-orion" },
        { name: "NPP (National Polar-orbiting Partnership)", link: "https://example.com/npp" }
    ],
    "O": [
        { name: "OSIRIS-REx", link: "https://example.com/osiris-rex" },
        { name: "OCO-2 (Orbiting Carbon Observatory-2)", link: "https://example.com/oco-2" },
        { name: "OceanSat-2", link: "https://example.com/oceansat-2" }
    ],
    "P": [
        { name: "PACE (Plankton, Aerosol, Cloud, Ocean Ecosystem)", link: "https://science.nasa.gov/mission/pace/" },
        { name: "Parker Solar Probe", link: "https://science.nasa.gov/mission/parker-solar-probe/" },
        { name: "PFMI (Pore Formation and Mobility Investigation)", link: "https://science.nasa.gov/mission/pfmi/" },
        { name: "PharmaSat", link: "https://science.nasa.gov/mission/pharmasat/" },
        { name: "Phoenix", link: "https://science.nasa.gov/mission/phoenix/" },
        { name: "Pioneer 0 (Able 1)", link: "https://science.nasa.gov/mission/pioneer-0-able1/" },
        { name: "Pioneer 1 (Able 2)", link: "https://science.nasa.gov/mission/pioneer-1-able-2/" },
        { name: "Pioneer 2", link: "https://science.nasa.gov/mission/pioneer-2/" },
        { name: "Pioneer 3", link: "https://science.nasa.gov/mission/pioneer-3/" },
        { name: "Pioneer 4", link: "https://science.nasa.gov/mission/pioneer-4/" },
        { name: "Pioneer 5", link: "https://science.nasa.gov/mission/pioneer-5/" },
        { name: "Pioneer 6", link: "https://science.nasa.gov/mission/pioneer-6/" },
        { name: "Pioneer 7", link: "https://science.nasa.gov/mission/pioneer-7/" },
        { name: "Pioneer 8", link: "https://science.nasa.gov/mission/pioneer-8/" },
        { name: "Pioneer 9", link: "https://science.nasa.gov/mission/pioneer-9/" },
        { name: "Pioneer 10", link: "https://science.nasa.gov/mission/pioneer-10/" },
        { name: "Pioneer 11", link: "https://science.nasa.gov/mission/pioneer-11/" },
        { name: "Pioneer-E", link: "https://science.nasa.gov/mission/pioneer-e/" },
        { name: "Pioneer Venus 1", link: "https://science.nasa.gov/mission/pioneer-venus-1/" },
        { name: "Pioneer Venus 2", link: "https://science.nasa.gov/mission/pioneer-venus-2/" },
        { name: "Planck", link: "https://science.nasa.gov/mission/planck/" },
        { name: "Plasma Kristall-4", link: "https://science.nasa.gov/mission/pk-4/" },
        { name: "Polar", link: "https://science.nasa.gov/mission/polar/" },
        { name: "PREFIRE (Polar Radiant Energy in the Far-InfraRed Experiment)", link: "https://science.nasa.gov/mission/prefire/" },
        { name: "PRESat (PharmaSat Risk Evaluation Satellite)", link: "https://science.nasa.gov/mission/presat/" },
        { name: "PRIME-1 (Polar Resources Ice Mining Experiment-1)", link: "NA" },
        { name: "Project Mercury", link: "https://www.nasa.gov/project-mercury/" },
        { name: "Psyche", link: "https://science.nasa.gov/mission/psyche/" },
        { name: "PUNCH (Polarimeter to Unify the Corona and Heliosphere)", link: "https://science.nasa.gov/mission/punch/" }
      ],
    "Q": [
        { name: "Q-PACE (CubeSat Particle Aggregation and Collision Experiment)", link: "https://science.nasa.gov/mission/q-pace/" },
        { name: "Quesst (X-59)", link: "https://www.nasa.gov/mission/quesst/" },
        { name: "QuikSCAT (Quick Scatterometer)", link: "https://science.nasa.gov/mission/quikscat/" }
    ],
    "R": [
        { name: "RADARSAT-1 (Radar Satellite-1)", link: "https://science.nasa.gov/mission/radarsat-1/" },
        { name: "Ranger 1", link: "https://science.nasa.gov/mission/ranger-1/" },
        { name: "Ranger 2", link: "https://science.nasa.gov/mission/ranger-2/" },
        { name: "Ranger 3", link: "https://science.nasa.gov/mission/ranger-3/" },
        { name: "Ranger 4", link: "https://science.nasa.gov/mission/ranger-4/" },
        { name: "Ranger 5", link: "https://science.nasa.gov/mission/ranger-5/" },
        { name: "Ranger 6", link: "https://science.nasa.gov/mission/ranger-6/" },
        { name: "Ranger 7", link: "https://science.nasa.gov/mission/ranger-7/" },
        { name: "Ranger 8", link: "https://science.nasa.gov/mission/ranger-8/" },
        { name: "Ranger 9", link: "https://science.nasa.gov/mission/ranger-9/" },
        { name: "RapidScat (ISS-RapidScat)", link: "https://science.nasa.gov/mission/iss-rapidscat/" },
        { name: "Redstone 3 (Freedom 7)", link: "https://www.nasa.gov/mission/mercury-redstone-3-freedom-7/" },
        { name: "Redstone 4 (Liberty Bell 7)", link: "https://www.nasa.gov/mission/mercury-redstone-4-liberty-bell-7/" },
        { name: "RHESSI (Reuven Ramaty High Energy Solar Spectroscopic Imager)", link: "https://science.nasa.gov/mission/rhessi/" },
        { name: "Rodent Research", link: "https://science.nasa.gov/mission/rodent-research/" },
        { name: "Roman (Nancy Grace Roman Space Telescope)", link: "https://science.nasa.gov/mission/roman-space-telescope/" },
        { name: "ROSAT (ROentgen SATellite)", link: "https://science.nasa.gov/mission/rosat/" },
        { name: "Rosetta-Philae", link: "https://science.nasa.gov/mission/rosetta-philae/" },
        { name: "RXTE (Rossi X-ray Timing Explorer)", link: "https://science.nasa.gov/mission/rxte/" }
    ],
    "S": [
        { name: "SAC-B (Satelite de Aplicaciones Científicas)", link: "https://science.nasa.gov/mission/sac-b/" },
        { name: "SAGE III (Stratospheric Aerosol and Gas Experiment III)", link: "https://science.nasa.gov/mission/sage-3-iss/" },
        { name: "SAGE-III (SAGE-III Meteor 3M)", link: "https://science.nasa.gov/mission/sage-3-meteor-3m/" },
        { name: "Sakigake", link: "https://science.nasa.gov/mission/sakigake/" },
        { name: "SAMPEX (Solar, Anomalous, and Magnetospheric Particle Explorer)", link: "https://science.nasa.gov/mission/sampex/" },
        { name: "SEAC4RS (Studies of Emissions, Atmospheric Composition, Clouds and Climate Coupling by Regional Surveys)", link: "https://science.nasa.gov/mission/seac4rs/" },
        { name: "Seasat 1", link: "https://science.nasa.gov/mission/seasat/" },
        { name: "SeaWiFS (Sea-viewing Wide Field-of-view Sensor)", link: "https://science.nasa.gov/mission/seawifs/" },
        { name: "SeaWinds on ADEOS II (SeaWinds on the Advanced Earth Observing Satellite II (ADEOS II))", link: "https://science.nasa.gov/mission/seawinds/" },
        { name: "SET-1 (Space Environment Testbeds 1)", link: "https://science.nasa.gov/mission/set-1/" },
        { name: "Shuttle-Mir", link: "https://www.nasa.gov/space-shuttle/shuttle-mir/#:~:text=From%20early%201994%20into%201998,with%20Russia's%20space%20station%20Mir." },
        { name: "Skylab", link: "https://www.nasa.gov/mission/skylab/" },
        { name: "SDO (Solar Dynamics Observatory)", link: "https://science.nasa.gov/mission/sdo/" },
        { name: "Shuttle Imaging Radar (Shuttle Imaging Radar-C / X-Band Synthetic Aperture Radar)", link: "https://science.nasa.gov/mission/sir-c-x-sar/" },
        { name: "Small Satellite Missions", link: "NA" },
        { name: "SMAP (Soil Moisture Active Passive)", link: "https://science.nasa.gov/mission/smap/" },
        { name: "SMART-1 (Small Missions for Advanced Research in Technology)", link: "https://science.nasa.gov/mission/smart-1/" },
        { name: "SMS (Synchronous Meteorological Satellite)", link: "https://science.nasa.gov/mission/sms/" },
        { name: "SNOE (Student Nitric Oxide Explorer)", link: "https://science.nasa.gov/mission/snoe/" },
        { name: "SOFIA (Stratospheric Observatory for Infrared Astronomy)", link: "https://science.nasa.gov/mission/sofia/" },
        { name: "SoFIE (Solid Fuel Ignition and Extinction)", link: "https://science.nasa.gov/mission/sofie/" },
        { name: "SOHO (Solar and Heliospheric Observatory)", link: "https://science.nasa.gov/mission/soho/" },
        { name: "Solar Orbiter", link: "https://science.nasa.gov/mission/solar-orbiter/" },
        { name: "SORTIE (Scintillation Observations & Response of the Ionosphere to Electrodynamics)", link: "https://science.nasa.gov/mission/sortie/" },
        { name: "Solar Sail Demonstrator", link: "https://www.nasa.gov/tdm/solar-sail-demonstrator-sunjammer/" },
        { name: "SORCE (Solar Radiation and Climate Experiment)", link: "https://science.nasa.gov/mission/sorce/" },
        { name: "Space Shuttle Era", link: "https://www.nasa.gov/space-shuttle/" },
        { name: "Spartan 201", link: "https://science.nasa.gov/mission/spartan/" },
        { name: "SPHEREx (Spectro-Photometer for the History of the Universe and Ices Explorer)", link: "https://science.nasa.gov/mission/spherex/" },
        { name: "Spirit (Mars Exploration Rover – Spirit)", link: "https://science.nasa.gov/mission/mer-spirit/" },
        { name: "Spitzer Space Telescope", link: "https://science.nasa.gov/mission/spitzer/" },
        { name: "SRTM (Shuttle Radar Topography Mission)", link: "https://science.nasa.gov/mission/srtm/" },
        { name: "ST5", link: "https://science.nasa.gov/mission/space-technology-5/" },
        { name: "ST6", link: "https://science.nasa.gov/mission/space-technology-6/" },
        { name: "ST7", link: "https://science.nasa.gov/mission/space-technology-7-drs/" },
        { name: "Stardust / Stardust NExT", link: "https://science.nasa.gov/mission/stardust/" },
        { name: "STEREO A & B (Solar TErrestrial RElations Observatory)", link: "https://science.nasa.gov/mission/stereo/" },
        { name: "STS-1", link: "https://www.nasa.gov/mission/sts-1/" },
        { name: "STS-2", link: "https://www.nasa.gov/mission/sts-2/" },
        { name: "STS-3", link: "https://www.nasa.gov/mission/sts-3/" },
        { name: "STS-4", link: "https://www.nasa.gov/mission/sts-4/" },
        { name: "STS-5", link: "https://www.nasa.gov/mission/sts-5/" },
        { name: "STS-6", link: "https://www.nasa.gov/mission/sts-6/" },
        { name: "STS-7", link: "https://www.nasa.gov/mission/sts-7/" },
        { name: "STS-8", link: "https://www.nasa.gov/mission/sts-8/" },
        { name: "STS-9", link: "https://www.nasa.gov/mission/sts-9/" },
        { name: "STS-26", link: "https://www.nasa.gov/mission/sts-26/" },
        { name: "STS-27", link: "https://www.nasa.gov/mission/sts-27/" },
        { name: "STS-28", link: "https://www.nasa.gov/mission/sts-28/" },
        { name: "STS-29", link: "https://www.nasa.gov/mission/sts-29/" },
        { name: "STS-30", link: "https://www.nasa.gov/mission/sts-30/" },
        { name: "STS-31", link: "https://www.nasa.gov/mission/sts-31/" },
        { name: "STS-32", link: "https://www.nasa.gov/mission/sts-32/" },
        { name: "STS-33", link: "https://www.nasa.gov/mission/sts-33/" },
        { name: "STS-34", link: "https://www.nasa.gov/mission/sts-34/" },
        { name: "STS-35", link: "https://www.nasa.gov/mission/sts-35/" },
        { name: "STS-36", link: "https://www.nasa.gov/mission/sts-36/" },
        { name: "STS-37", link: "https://www.nasa.gov/mission/sts-37/" },
        { name: "STS-38", link: "https://www.nasa.gov/mission/sts-38/" },
        { name: "STS-39", link: "https://www.nasa.gov/mission/sts-39/" },
        { name: "STS-40", link: "https://www.nasa.gov/mission/sts-40/" },
        { name: "STS-41", link: "https://www.nasa.gov/mission/sts-41/" },
        { name: "STS-41B", link: "https://www.nasa.gov/mission/sts-41b/" },
        { name: "STS-41C", link: "https://www.nasa.gov/mission/sts-41c/" },
        { name: "STS-41D", link: "https://www.nasa.gov/mission/sts-41d/" },
        { name: "STS-41G", link: "https://www.nasa.gov/mission/sts-41g/" },
        { name: "STS-42", link: "https://www.nasa.gov/mission/sts-42/" },
        { name: "STS-43", link: "https://www.nasa.gov/mission/sts-43/" },
        { name: "STS-44", link: "https://www.nasa.gov/mission/sts-44/" },
        { name: "STS-45", link: "https://www.nasa.gov/mission/sts-45/" },
        { name: "STS-46", link: "https://www.nasa.gov/mission/sts-46/" },
        { name: "STS-47", link: "https://www.nasa.gov/mission/sts-47/" },
        { name: "STS-48", link: "https://www.nasa.gov/mission/sts-48/" },
        { name: "STS-49", link: "https://www.nasa.gov/mission/sts-49/" },
        { name: "STS-50", link: "https://www.nasa.gov/mission/sts-50/" },
        { name: "STS-51", link: "https://www.nasa.gov/mission/sts-51/" },
        { name: "STS-51A", link: "https://www.nasa.gov/mission/sts-51a/" },
        { name: "STS-51B", link: "https://www.nasa.gov/mission/sts-51b/" },
        { name: "STS-51C", link: "https://www.nasa.gov/mission/sts-51c/" },
        { name: "STS-51D", link: "https://www.nasa.gov/mission/sts-51d/" },
        { name: "STS-51F", link: "https://www.nasa.gov/mission/sts-51f/" },
        { name: "STS-51G", link: "https://www.nasa.gov/mission/sts-51g/" },
        { name: "STS-51I", link: "https://www.nasa.gov/mission/sts-51i/" },
        { name: "STS-51J", link: "https://www.nasa.gov/mission/sts-51j/" },
        { name: "STS-51L", link: "https://www.nasa.gov/mission/sts-51l/" },
        { name: "STS-52", link: "https://www.nasa.gov/mission/sts-52/" },
        { name: "STS-53", link: "https://www.nasa.gov/mission/sts-53/" },
        { name: "STS-54", link: "https://www.nasa.gov/mission/sts-54/" },
        { name: "STS-55", link: "https://www.nasa.gov/mission/sts-55/" },
        { name: "STS-56", link: "https://www.nasa.gov/mission/sts-56/" },
        { name: "STS-57", link: "https://www.nasa.gov/mission/sts-57/" },
        { name: "STS-58", link: "https://www.nasa.gov/mission/sts-58/" },
        { name: "STS-59", link: "https://www.nasa.gov/mission/sts-59/" },
        { name: "STS-60", link: "https://www.nasa.gov/mission/sts-60/" },
        { name: "STS-61", link: "https://www.nasa.gov/mission/sts-61/" },
        { name: "STS-61A", link: "https://www.nasa.gov/mission/sts-61a/" },
        { name: "STS-61B", link: "https://www.nasa.gov/mission/sts-61b/" },
        { name: "STS-61C", link: "https://www.nasa.gov/mission/sts-61c/" },
        { name: "STS-62", link: "https://www.nasa.gov/mission/sts-62/" },
        { name: "STS-63", link: "https://www.nasa.gov/mission/sts-63/" },
        { name: "STS-64", link: "https://www.nasa.gov/mission/sts-64/" },
        { name: "STS-65", link: "https://www.nasa.gov/mission/sts-65/" },
        { name: "STS-66", link: "https://www.nasa.gov/mission/sts-66/" },
        { name: "STS-67", link: "https://www.nasa.gov/mission/sts-67/" },
        { name: "STS-68", link: "https://www.nasa.gov/mission/sts-68/" },
        { name: "STS-69", link: "https://www.nasa.gov/mission/sts-69/" },
        { name: "STS-70", link: "https://www.nasa.gov/mission/sts-70/" },
        { name: "STS-71", link: "https://www.nasa.gov/mission/sts-71/" },
        { name: "STS-72", link: "https://www.nasa.gov/mission/sts-72/" },
        { name: "STS-73", link: "https://www.nasa.gov/mission/sts-73/" },
        { name: "STS-74", link: "https://www.nasa.gov/mission/sts-74/" },
        { name: "STS-75", link: "https://www.nasa.gov/mission/sts-75/" },
        { name: "STS-76", link: "https://www.nasa.gov/mission/sts-76/" },
        { name: "STS-77", link: "https://www.nasa.gov/mission/sts-77/" },
        { name: "STS-78", link: "https://www.nasa.gov/mission/sts-78/" },
        { name: "STS-79", link: "https://www.nasa.gov/mission/sts-79/" },
        { name: "STS-80", link: "https://www.nasa.gov/mission/sts-80/" },
        { name: "STS-81", link: "https://www.nasa.gov/mission/sts-81/" },
        { name: "STS-82", link: "https://www.nasa.gov/mission/sts-82/" },
        { name: "STS-83", link: "https://www.nasa.gov/mission/sts-83/" },
        { name: "STS-84", link: "https://www.nasa.gov/mission/sts-84/" },
        { name: "STS-85", link: "https://www.nasa.gov/mission/sts-85/" },
        { name: "STS-86", link: "https://www.nasa.gov/mission/sts-86/" },
        { name: "STS-87", link: "https://www.nasa.gov/mission/sts-87/" },
        { name: "STS-88", link: "https://www.nasa.gov/mission/sts-88/" },
        { name: "STS-89", link: "https://www.nasa.gov/mission/sts-89/" },
        { name: "STS-90", link: "https://www.nasa.gov/mission/sts-90/" },
        { name: "STS-91", link: "https://www.nasa.gov/mission/sts-91/" },
        { name: "STS-92", link: "https://www.nasa.gov/mission/sts-92/" },
        { name: "STS-93", link: "https://www.nasa.gov/mission/sts-93/" },
        { name: "STS-94", link: "https://www.nasa.gov/mission/sts-94/" },
        { name: "STS-95", link: "https://www.nasa.gov/mission/sts-95/" },
        { name: "STS-96", link: "https://www.nasa.gov/mission/sts-96/" },
        { name: "STS-97", link: "https://www.nasa.gov/mission/sts-97/" },
        { name: "STS-98", link: "https://www.nasa.gov/mission/sts-98/" },
        { name: "STS-99", link: "https://www.nasa.gov/mission/sts-99/" },
        { name: "STS-100", link: "https://www.nasa.gov/mission/sts-100/" },
        { name: "STS-101", link: "https://www.nasa.gov/mission/sts-101/" },
        { name: "STS-102", link: "https://www.nasa.gov/mission/sts-102/" },
        { name: "STS-103", link: "https://www.nasa.gov/mission/sts-103/" },
        { name: "STS-104", link: "https://www.nasa.gov/mission/sts-104/" },
        { name: "STS-105", link: "https://www.nasa.gov/mission/sts-105/" },
        { name: "STS-106", link: "https://www.nasa.gov/mission/sts-106/" },
        { name: "STS-107", link: "https://www.nasa.gov/mission/sts-107/" },
        { name: "STS-108", link: "https://www.nasa.gov/mission/sts-108/" },
        { name: "STS-109", link: "https://www.nasa.gov/mission/sts-109/" },
        { name: "STS-110", link: "https://www.nasa.gov/mission/sts-110/" },
        { name: "STS-111", link: "https://www.nasa.gov/mission/sts-111/" },
        { name: "STS-112", link: "https://www.nasa.gov/mission/sts-112/" },
        { name: "STS-113", link: "https://www.nasa.gov/mission/sts-113/" },
        { name: "STS-114", link: "https://www.nasa.gov/mission/sts-114/" },
        { name: "STS-115", link: "https://www.nasa.gov/mission/sts-115/" },
        { name: "STS-116", link: "https://www.nasa.gov/mission/sts-116/" },
        { name: "STS-117", link: "https://www.nasa.gov/mission/sts-117/" },
        { name: "STS-118", link: "https://www.nasa.gov/mission/sts-118/" },
        { name: "STS-119", link: "https://www.nasa.gov/mission/sts-119/" },
        { name: "STS-120", link: "https://www.nasa.gov/mission/sts-120/" },
        { name: "STS-121", link: "https://www.nasa.gov/mission/sts-121/" },
        { name: "STS-122", link: "https://www.nasa.gov/mission/sts-122/" },
        { name: "STS-123", link: "https://www.nasa.gov/mission/sts-123/" },
        { name: "STS-124", link: "https://www.nasa.gov/mission/sts-124/" },
        { name: "STS-125", link: "https://www.nasa.gov/mission/sts-125/" },
        { name: "STS-126", link: "https://www.nasa.gov/mission/sts-126/" },
        { name: "STS-127", link: "https://www.nasa.gov/mission/sts-127/" },
        { name: "STS-128", link: "https://www.nasa.gov/mission/sts-128/" },
        { name: "STS-129", link: "https://www.nasa.gov/mission/sts-129/" },
        { name: "STS-130", link: "https://www.nasa.gov/mission/sts-130/" },
        { name: "STS-131", link: "https://www.nasa.gov/mission/sts-131/" },
        { name: "STS-132", link: "https://www.nasa.gov/mission/sts-132/" },
        { name: "STS-133", link: "https://www.nasa.gov/mission/sts-133/" },
        { name: "STS-134", link: "https://www.nasa.gov/mission/sts-134/" },
        { name: "STS-135", link: "https://www.nasa.gov/mission/sts-135/" },
        { name: "SUBSA (Solidification Using a Baffle in Sealed Ampoules)", link: "https://science.nasa.gov/mission/subsa/" },
        { name: "SunRISE (Sun Radio Interferometer Space Experiment)", link: "https://science.nasa.gov/mission/sunrise/" },
        { name: "Suomi NPP (Suomi National Polar-orbiting Partnership)", link: "https://science.nasa.gov/mission/suomi-npp/" },
        { name: "Surveyor 1", link: "https://science.nasa.gov/mission/surveyor-1/" },
        { name: "Surveyor 2", link: "https://science.nasa.gov/mission/surveyor-2/" },
        { name: "Surveyor 3", link: "https://science.nasa.gov/mission/surveyor-3/" },
        { name: "Surveyor 4", link: "https://science.nasa.gov/mission/surveyor-4/" },
        { name: "Surveyor 5", link: "https://science.nasa.gov/mission/surveyor-5/" },
        { name: "Surveyor 6", link: "https://science.nasa.gov/mission/surveyor-6/" },
        { name: "Surveyor 7", link: "https://science.nasa.gov/mission/surveyor-7/" },
        { name: "Surveyor Model 1", link: "https://science.nasa.gov/mission/surveyor-model-1/" },
        { name: "Surveyor Model 2", link: "https://science.nasa.gov/mission/surveyor-model-2/" },
        { name: "Suzaku", link: "https://science.nasa.gov/mission/suzaku/" },
        { name: "SWAS (Submillimeter Wave Astronomy Satellite)", link: "https://science.nasa.gov/mission/swas/" },
        { name: "Swift Space Observatory", link: "https://science.nasa.gov/mission/swift/" },
        { name: "SWOT (Surface Water and Ocean Topography)", link: "https://science.nasa.gov/mission/swot/" }
    ],
    "T": [
        { name: "TDRS (Tracking and Data Relay Satellite)", link: "https://www.nasa.gov/mission/tracking-and-data-relay-satellites/" },
        { name: "Technology Demonstration Missions", link: "https://www.nasa.gov/tdm/" },
        { name: "Telerobotics", link: "https://www.nasa.gov/tdm/human-exploration-telerobotics-het/" },
        { name: "TEMPO (Tropospheric Emissions: Monitoring of POllution)", link: "https://science.nasa.gov/mission/tempo/" },
        { name: "Terra", link: "https://science.nasa.gov/mission/terra/" },
        { name: "Terriers (Tomographic Experiment Using Radiative Recombinative Ionospheric EUV and Radio Sources)", link: "https://science.nasa.gov/mission/terriers/" },
        { name: "TESS (Transiting Exoplanet Survey Satellite)", link: "https://science.nasa.gov/mission/tess/" },
        { name: "THEMIS Science (Time History of Events and Macroscale Interactions During Substorms)", link: "https://science.nasa.gov/mission/themis/" },
        { name: "TIMED (Thermosphere Ionosphere Mesosphere Energetics and Dynamics)", link: "https://science.nasa.gov/mission/timed/" },
        { name: "TIROS (Television Infrared Observation Satellite Program)", link: "https://science.nasa.gov/mission/tiros/" },
        { name: "TOMS-EP (Total Ozone Mapping Spectrometer-Earth Probe)", link: "https://science.nasa.gov/mission/toms-ep/" },
        { name: "TOPEX/Poseidon", link: "https://science.nasa.gov/mission/topex-poseidon/" },
        { name: "TRACE (Transition Region And Coronal Explorer)", link: "https://science.nasa.gov/mission/trace/" },
        { name: "TRACER-AQ (Tracking Aerosol Convection Interactions Experiment-Air Quality)", link: "https://science.nasa.gov/mission/tracer/" },
        { name: "TRMM (Tropical Rainfall Measuring Mission)", link: "https://science.nasa.gov/mission/trmm/" },
        { name: "TROPICS (Time-Resolved Observations of Precipitation structure and storm Intensity with a Constellation of Smallsats)", link: "https://science.nasa.gov/mission/tropics/" },
        { name: "TSIS-1 (Total and Spectral Solar Irradiance Sensor)", link: "https://science.nasa.gov/mission/tsis-1/" },
        { name: "TSIS-2 (Total and Spectral Solar Irradiance Sensor)", link: "https://science.nasa.gov/mission/tsis-2/" },
        { name: "TSS (Tethered Satellite System)", link: "https://science.nasa.gov/mission/tss/" },
        { name: "TWINS (Two Wide-angle Imaging Neutral-atom Spectrometers)", link: "https://science.nasa.gov/mission/twins/" }
    ]
    ,
    "U": [
        { name: "UARS (Upper Atmosphere Research Satellite)", link: "https://science.nasa.gov/mission/uars/" },
        { name: "Ulysses", link: "https://science.nasa.gov/mission/ulysses/" }
    ],
    "V": [
        { name: "Van Allen Probes", link: "https://science.nasa.gov/mission/van-allen-probes/" },
        { name: "VEGGIE (Vegetable Production System)", link: "https://science.nasa.gov/mission/veggie/" },
        { name: "Venus Express", link: "https://science.nasa.gov/mission/venus-express/" },
        { name: "VERITAS (Venus Emissivity, Radio Science, InSAR, Topography and Spectroscopy)", link: "https://science.nasa.gov/mission/veritas/" },
        { name: "Viking 1", link: "https://science.nasa.gov/mission/viking-1/" },
        { name: "Viking 2", link: "https://science.nasa.gov/mission/viking-2/" },
        { name: "VIPER (Volatiles Investigating Polar Exploration Rover)", link: "https://science.nasa.gov/mission/viper/" },
        { name: "Voyager 1", link: "https://science.nasa.gov/mission/voyager/voyager-1/" },
        { name: "Voyager 2", link: "https://science.nasa.gov/mission/voyager/voyager-2/" },
        { name: "Voyager Program", link: "https://science.nasa.gov/mission/voyager/" }
    ],
    "W": [
        { name: "WetLab-2", link: "https://science.nasa.gov/mission/wetlab-2/" },
        { name: "Wind", link: "https://science.nasa.gov/mission/wind/" },
        { name: "WIRE (Wide-field InfraRed Explorer)", link: "https://science.nasa.gov/mission/wire/" },
        { name: "WISE/NEOWISE (Near-Earth Object Wide Field Infrared Survey Explorer)", link: "https://science.nasa.gov/mission/neowise/" },
        { name: "WMAP (Wilkinson Microwave Anisotropy Probe)", link: "https://science.nasa.gov/mission/wmap/" }
    ],
    "X": [
        { name: "XMM-Newton (X-ray Multi-Mirror Mission Newton)", link: "https://science.nasa.gov/mission/xmm-newton/" },
        { name: "XRISM (X-ray Imaging and Spectroscopy Mission)", link: "https://science.nasa.gov/mission/xrism/" }
    ],
    "Y": [
        { name: "Yohkoh", link: "https://science.nasa.gov/mission/yohkoh/" }
    ],
    "Z": [
        { name: "ZBOT-NC (Zero Boil-Off Tank-Non-Condensable)", link: "https://science.nasa.gov/mission/zbot-nc/" }
    ],
    "NUM": [
        { name: "3D Tissue Chips", link: "https://science.nasa.gov/mission/3d-tissue-chips/" }
    ]
}

export default missions;